version: '3.3'

services: 
  web_server:
    depends_on: 
      - image_extraction_server
    image: nginx:1.18-alpine
    container_name: web-server
    restart: always
    ports: 
      - 8080:80
    volumes:
      - ./config:/etc/nginx/conf.d
      - www-data:/var/www
    
  image_extraction_server:
    build: .
    container_name: image-extraction-server
    restart: always
    volumes: 
      - www-data:/var/www
      - ../hkcic-web/build:/var/www/hkcic-web
      
volumes: 
  www-data:

